name: Generate Keystore (one-time use)

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generar el keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore release.keystore \
            -alias mibrave \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "Y#\,6FjOl?2gnOs" \
            -keypass "Y#\,6FjOl?2gnOs" \
            -dname "CN=Personal Use, OU=Personal Use, O=Personal Use, L=Unknown, S=Unknown, C=XX"

          base64 -w 0 release.keystore > keystore-base64.txt

      - name: Subir como artifact temporal
        uses: actions/upload-artifact@v4
        with:
          name: keystore-output
          path: keystore-base64.txt
          retention-days: 1
